// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCz6htlUY4TS61HjHpbWpOPDoCcMt3iM',
    appId: '1:553199717680:web:24cc97f7c23d50ca1a4cf5',
    messagingSenderId: '553199717680',
    projectId: 'proyecto-serrainnova',
    authDomain: 'proyecto-serrainnova.firebaseapp.com',
    storageBucket: 'proyecto-serrainnova.firebasestorage.app',
    measurementId: 'G-ME1N1K4KS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYCAfwmW84FcUErIcCYRvmtSDwq01X0E',
    appId: '1:553199717680:android:f54a2121993ddae21a4cf5',
    messagingSenderId: '553199717680',
    projectId: 'proyecto-serrainnova',
    storageBucket: 'proyecto-serrainnova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZGOPxVMc4OyQeK1Uu6brUtstWsmGY68',
    appId: '1:553199717680:ios:51cc73f84920c5bf1a4cf5',
    messagingSenderId: '553199717680',
    projectId: 'proyecto-serrainnova',
    storageBucket: 'proyecto-serrainnova.firebasestorage.app',
    iosBundleId: 'com.example.serrainnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEZGOPxVMc4OyQeK1Uu6brUtstWsmGY68',
    appId: '1:553199717680:ios:51cc73f84920c5bf1a4cf5',
    messagingSenderId: '553199717680',
    projectId: 'proyecto-serrainnova',
    storageBucket: 'proyecto-serrainnova.firebasestorage.app',
    iosBundleId: 'com.example.serrainnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCz6htlUY4TS61HjHpbWpOPDoCcMt3iM',
    appId: '1:553199717680:web:52972cc31e730fc71a4cf5',
    messagingSenderId: '553199717680',
    projectId: 'proyecto-serrainnova',
    authDomain: 'proyecto-serrainnova.firebaseapp.com',
    storageBucket: 'proyecto-serrainnova.firebasestorage.app',
    measurementId: 'G-8H4L1J0PC7',
  );
}
